cookie:
  expiry_days: 3000
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    joeadmin:
      email: Joeadmin@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Joe Admin
      password: $2b$12$Deb7XFffs7FwspZx4vuavu9JwPf8zSQh.VnFxDZR9W9qvZPEfvDNu
      role: admin
    joeuser:
      email: Joeuser@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Joe User
      password: $2b$12$xMDAR4gCWwcooSebUV/CY.Vecxdwm3Qs0kwSwwUVt/BaSfTvz7d..
      role: user
preauthorized:
  emails:
  - kieran.raj2006@gmail.com
